// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pars_ConfigurationServices.Data;

#nullable disable

namespace ParsConfigurationServices.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pars_ConfigurationServices.Models.AdminPermission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isAdmin");

                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("id");

                    b.ToTable("AdminPermission");
                });

            modelBuilder.Entity("Pars_ConfigurationServices.Models.SchoolConfiguration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("absenceColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("absenceColor");

                    b.Property<string>("lateColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lateColor");

                    b.Property<int>("numberOfStudents")
                        .HasColumnType("int")
                        .HasColumnName("numberOfStudents");

                    b.Property<string>("presenceColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("presenceColor");

                    b.Property<int>("schoolId")
                        .HasColumnType("int")
                        .HasColumnName("schoolId");

                    b.HasKey("id");

                    b.ToTable("SchoolConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
