// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pars_ScheduleManagement.DAL.Context;

#nullable disable

namespace Pars_ScheduleManagement.DAL.Migrations
{
    [DbContext(typeof(ScheduleManagementDbContext))]
    [Migration("20240110092701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.ClassRoom", b =>
                {
                    b.Property<Guid>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassRoomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassRoomId");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LessonId");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("LessonId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.Teacher", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.Lesson", b =>
                {
                    b.HasOne("Pars_ScheduleManagement.DAL.Models.ClassRoom", "classRoom")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassRoomId");

                    b.HasOne("Pars_ScheduleManagement.DAL.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");

                    b.Navigation("classRoom");
                });

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.Student", b =>
                {
                    b.HasOne("Pars_ScheduleManagement.DAL.Models.Lesson", null)
                        .WithMany("students")
                        .HasForeignKey("LessonId");
                });

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.ClassRoom", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Pars_ScheduleManagement.DAL.Models.Lesson", b =>
                {
                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
