@startuml test3
title C2 Diagram Example 3
!include <C4/C4_Container>

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

System_Ext(extSystemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Go")

Rel_U(systemAlias, extSystemAlias, "Label", "Go")
@enduml