// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pars_UserValidation.DAL.Context;

#nullable disable

namespace Pars_UserValidation.DAL.Migrations
{
    [DbContext(typeof(UserValidationDbContext))]
    partial class UserValidationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.ClassRoom", b =>
                {
                    b.Property<Guid>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassRoomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassRoomId");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LessonId");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("LessonId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.Teacher", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.UserValidationModel", b =>
                {
                    b.Property<Guid>("UserValidationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StudentPresence")
                        .HasColumnType("int");

                    b.Property<Guid>("TUId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserValidation_Lesson_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserValidation_Student_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserValidation_Teacher_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserValidationId");

                    b.HasIndex("UserValidation_Lesson_FK");

                    b.HasIndex("UserValidation_Student_FK");

                    b.HasIndex("UserValidation_Teacher_FK");

                    b.ToTable("UserValidation");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.Lesson", b =>
                {
                    b.HasOne("Pars_UserValidation.DAL.Models.ClassRoom", "classRoom")
                        .WithMany("lessons")
                        .HasForeignKey("ClassRoomId");

                    b.HasOne("Pars_UserValidation.DAL.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");

                    b.Navigation("classRoom");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.Student", b =>
                {
                    b.HasOne("Pars_UserValidation.DAL.Models.Lesson", null)
                        .WithMany("students")
                        .HasForeignKey("LessonId");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.UserValidationModel", b =>
                {
                    b.HasOne("Pars_UserValidation.DAL.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("UserValidation_Lesson_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pars_UserValidation.DAL.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("UserValidation_Student_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pars_UserValidation.DAL.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("UserValidation_Teacher_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.ClassRoom", b =>
                {
                    b.Navigation("lessons");
                });

            modelBuilder.Entity("Pars_UserValidation.DAL.Models.Lesson", b =>
                {
                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
