name: Documentation generation and publish

on:
    push:
        branches: [ main, develop ]
    workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Check Bash interpreter path
      run: which bash
    - name: Install puml package globally
      run: npm install -g asciidoctor
    - name: Install asciidoctor package globally
      run: npm install -g puml
    - name: Run bash script
      run: |
        sed -i -e 's/\r$//' ./Shared/Documentation/generate_documentation.sh
        chmod +x Shared/Documentation/generate_documentation.sh
        ./Shared/Documentation/generate_documentation.sh
      shell: bash

